[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
# Defina VITE_TMDB_V4 no painel do Netlify (Site settings → Build & deploy → Environment variables).
# Aqui apenas documentamos que a variável é esperada em produção.
VITE_TMDB_V4 = ""
